import { useEffect, useRef, useState, type PointerEvent } from "react"

import Footer from "../../components/Footer/Footer"
import Navbar from "../../components/Navbar/Navbar"
import SEO from "../../components/SEO/SEO"
import { categories } from "../../data/categories"
import { getMeals } from "../../services/meals"
import type { Category, Meal } from "../../types/meal"

import "./_menu.scss"

const priceFormatter = new Intl.NumberFormat("es-AR", {
  style: "currency",
  currency: "ARS"
})

const dragThreshold = 6

// Displays the public menu and filters available meals by the selected category.
const Menu = () => {
  const [selectedCategory, setSelectedCategory] = useState<Category | null>(null)
  const [meals, setMeals] = useState<Meal[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [isDraggingCategories, setIsDraggingCategories] = useState(false)

  const categoryScrollerRef = useRef<HTMLElement>(null)
  const suppressCategoryClickRef = useRef(false)
  const categoryDragRef = useRef({ pointerId: -1, startX: 0, scrollLeft: 0, dragged: false })

  useEffect(() => {
    // Loads only meals marked as available so hidden products never reach the public list.
    const fetchMeals = async () => {
      setLoading(true)
      setError("")

      try {
        setMeals(await getMeals(true))
      } catch (error) {
        console.error("Failed to load the public menu:", error)
        setError("No se pudo cargar la carta. Intentá nuevamente.")
      } finally {
        setLoading(false)
      }
    }

    fetchMeals()
  }, [])

  const filteredMeals = selectedCategory
    ? meals.filter((meal) => meal.category === selectedCategory)
    : []

  // Stores the initial pointer position so a short press remains a category click.
  const handleCategoryPointerDown = (event: PointerEvent<HTMLElement>) => {
    if (event.pointerType === "mouse" && event.button !== 0) return

    const scroller = categoryScrollerRef.current
    if (!scroller) return

    suppressCategoryClickRef.current = false
    categoryDragRef.current = {
      pointerId: event.pointerId,
      startX: event.clientX,
      scrollLeft: scroller.scrollLeft,
      dragged: false
    }
  }

  // Scrolls the category row only after the pointer moves far enough to count as a drag.
  const handleCategoryPointerMove = (event: PointerEvent<HTMLElement>) => {
    const scroller = categoryScrollerRef.current
    const drag = categoryDragRef.current

    if (!scroller || drag.pointerId !== event.pointerId) return

    const distance = event.clientX - drag.startX

    if (!drag.dragged && Math.abs(distance) < dragThreshold) return

    if (!drag.dragged) {
      drag.dragged = true
      scroller.setPointerCapture(event.pointerId)
      setIsDraggingCategories(true)
    }

    event.preventDefault()
    scroller.scrollLeft = drag.scrollLeft - distance
  }

  // Ends the drag and suppresses the click generated by the same pointer gesture.
  const finishCategoryDrag = (event: PointerEvent<HTMLElement>) => {
    const scroller = categoryScrollerRef.current
    const drag = categoryDragRef.current

    if (drag.pointerId !== event.pointerId) return

    suppressCategoryClickRef.current = drag.dragged

    if (scroller?.hasPointerCapture(event.pointerId)) {
      scroller.releasePointerCapture(event.pointerId)
    }

    categoryDragRef.current = { pointerId: -1, startX: 0, scrollLeft: 0, dragged: false }
    setIsDraggingCategories(false)
  }

  // Selects a category only when the gesture was a click or tap instead of a drag.
  const handleCategoryClick = (category: Category) => {
    if (suppressCategoryClickRef.current) {
      suppressCategoryClickRef.current = false
      return
    }

    setSelectedCategory(category)
  }

  return (
    <>
      <SEO
        title="Carta | Mathilde Resto"
        description="Conocé la carta de Mathilde Resto: desayunos, entradas, platos principales, postres, bebidas y más."/>

      <Navbar/>

      <main className="menu">
        <nav
          ref={categoryScrollerRef}
          className={`menuCategories ${isDraggingCategories ? "menuCategories--dragging" : ""}`}
          aria-label="Categorías de la carta"
          onPointerDown={handleCategoryPointerDown}
          onPointerMove={handleCategoryPointerMove}
          onPointerUp={finishCategoryDrag}
          onPointerCancel={finishCategoryDrag}>
          <div className="menuCategoryList">
            {categories.map((category) => (
              <button
                key={category}
                type="button"
                className={`menuCategory ${selectedCategory === category ? "menuCategory--active" : ""}`}
                onClick={() => handleCategoryClick(category)}
                aria-pressed={selectedCategory === category}
                aria-controls="menuMeals">
                {category}
              </button>
            ))}
          </div>
        </nav>

        <section className="menuContent" id="menuMeals" aria-labelledby="menuTitle">
          <h1 className="menuTitle" id="menuTitle">Nuestra carta</h1>

          {loading && <p className="menuMessage" role="status" aria-live="polite">Cargando carta...</p>}
          {error && <p className="menuMessage menuMessage--error" role="alert">{error}</p>}

          {!loading && !error && selectedCategory && filteredMeals.length === 0 && (
            <p className="menuMessage">No hay comidas disponibles en esta categoría.</p>
          )}

          {!loading && !error && selectedCategory && filteredMeals.length > 0 && (
            <div className="meals">
              {filteredMeals.map((meal) => (
                <article className="meal" key={meal.id}>
                  <h2 className="mealName">{meal.name}</h2>
                  {meal.description && <p className="mealDescription">{meal.description}</p>}
                  {meal.price > 0 && <span className="mealPrice">{priceFormatter.format(meal.price)}</span>}
                  <div className="mealDivider" aria-hidden="true"/>
                </article>
              ))}
            </div>
          )}
        </section>

        {!loading && !error && !selectedCategory && (
          <p className="menuPrompt" role="status">¡Elegí una categoría y comenzá a explorar!</p>
        )}
      </main>

      <Footer/>
    </>
  )
}

export default Menu
